version: "3"

services:

  app:
    container_name: app
    build:
      context: .
      args:
        BUCKET_KEY_ID: ${BUCKET_KEY_ID}
        BUCKET_KEY: ${BUCKET_KEY}
        REGION: ${REGION}
    ports:
      - '8000:8000'
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"