version: "3"

services:

  app:
    container_name: app
    build:
      context: .
      args:
        BUCKET_KEY_ID: YCAJE2704dRnl9lCapZI7qWcP
        BUCKET_KEY: YCOU25ZS2Gem77ajtSfwZ6F7_i9DPWSV9o1aWrf5
        REGION: ru-central1 
    command: bash -c "python3 prepare.py && python3 train.py && python3 test.py"