stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/data/dataset.csv
    - src/prepare.py
    outs:
    - src/data/test.csv
    - src/data/train.csv
  train:
    cmd: python src/train.py
    deps:
    - src/data/train.csv
    - src/train.py
    outs:
    - src/data/weights.joblib
    params:
    - train
  test:
    cmd: python src/test.py
    deps:
    - src/data/test.csv
    - src/data/weights.joblib
    - src/test.py
    metrics:
    - src/data/metrics.json:
        cache: false
