stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/dataset.csv
    - src/prepare.py
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/train.csv
    - train.py
    outs:
    - data/weights.joblib
    params:
    - configs/hyperparams.yaml
      - train
  test:
    cmd: python src/test.py
    deps:
    - data/test.csv
    - data/weights.joblib
    - test.py
    metrics:
    - data/metrics.json:
        cache: false
