stages:
  prepare:
    cmd: python src/prepare.py --config_path configs/prepare.yaml
    deps:
    - data/dataset.csv
    - src/prepare.py
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python src/train.py --config_path configs/train.yaml
    deps:
    - data/train.csv
    - src/train.py
    outs:
    - data/weights.joblib
    params:
      - train
  test:
    cmd: python src/test.py --config_path configs/test.yaml
    deps:
    - data/test.csv
    - data/weights.joblib
    - src/test.py
    metrics:
    - data/metrics.json:
        cache: false
